Added pgsql driver
madecomfy/php7-v8js pull request #2
Opened 2017-12-27 12:53 UTC by pifagor87

Added pgsql driver for connecting DB PostgreSQL

2017-12-27 13:37 UTC, tomjowitt requested changes

2017-12-27 13:37 UTC, tomjowitt commented on Dockerfile
> +RUN phpenmod pdo_mysql && phpenmod pdo_pgsql
Hey, thanks for the PR but running phpenmod is not part of our build process as we prefer to configure our Docker containers with project-specific php.ini files. I'm happy to add the Postgres extension if you remove the phphenmod line.

2017-12-27 13:56 UTC, pifagor87 commented
I deleted the phphenmod line

2017-12-28 08:32 UTC, tomjowitt approved these changes

2018-01-02 01:48 UTC, merged